AgentTaskFlow
bharatpe/captain-app-automation pull request #4
Opened 2023-05-17 12:34 UTC by mauryaakash021

2023-05-19 05:59 UTC, jitendrapisal55 requested changes
@mauryaakash021  Please check the comments

2023-05-19 05:59 UTC, jitendrapisal55 commented on src/test/java/com/bharatpe/steps/AgentTaskSteps.java
> +
@mauryaakash021  remove extra spaces

2023-05-19 05:59 UTC, jitendrapisal55 commented on src/test/java/com/bharatpe/steps/AgentTaskSteps.java
> +            ;
@mauryaakash021  align your code. 
e.g - Open the file that you want to align.
Press  Command + option + L

2023-05-19 05:59 UTC, jitendrapisal55 commented on src/test/resources/features/agentTask.feature
> +    Then agent confirms the task
@mauryaakash021  remove this from background.
And create method like this in AgentTaskSteps

```
static boolean runOnlyOnce = true;

    @Before("@agent-tasks")
    public static void createTaskInit() {
        if (runOnlyOnce) {
            // call the method that are in the background here.
        }
        runOnlyOnce = false;
    }
```

2023-05-19 06:08 UTC, mauryaakash021 commented on src/test/java/com/bharatpe/steps/AgentTaskSteps.java
> +            ;
@jitendrapisal55     i Will take care in future.

2023-05-24 13:53 UTC, jitendrapisal55 commented on src/test/resources/features/agentTask.feature
> +    Then agent confirms the task
@mauryaakash021  work on it immediately

2023-05-25 04:57 UTC, mauryaakash021 commented on src/test/resources/features/agentTask.feature
> +    Then agent confirms the task
@jitendrapisal55   i have resolved it and pushed also.

2023-06-01 07:22 UTC, jitendrapisal55 approved these changes

2023-06-01 07:23 UTC, merged